[build]
publish = "public"
functions = "netlify/functions"

[functions]
external_node_modules = ["@sparticuz/chromium"]
node_bundler = "esbuild"

[functions."generate-story"]
included_files = ["public/**"]
timeout = 25

[functions."generate-brochure"]
included_files = ["public/**"]
timeout = 25