# netlify.toml

[build]
  publish = "public"
  functions = "netlify/functions"

  [build.environment]
  NEON_DATABASE_URL = "psql 'postgresql://neondb_owner:npg_xEhdgM95Bmon@ep-cool-thunder-adxeoa1r-pooler.c-2.us-east-1.aws.neon.tech/neondb?sslmode=require&channel_binding=require'"

[functions]
  external_node_modules = ["@sparticuz/chromium"]
  node_bundler = "esbuild"

[functions."generate-story"]
  timeout = 25