[build]
  publish = "public"
  functions = "netlify/functions"

[functions]
  node_bundler = "esbuild"

# Konfigurasi spesifik untuk setiap fungsi
[[functions]]
  path = "netlify/functions/generate-brochure.js"
  node_bundler = "esbuild"
  timeout = 25
  included_files = ["public/**"]

[[functions]]  
  path = "netlify/functions/cache-jadwal-data.js"
  node_bundler = "esbuild"
  timeout = 25
  included_files = ["public/**"]

[[functions]]
  path = "netlify/functions/generate-story.js" 
  node_bundler = "esbuild"
  timeout = 25
  included_files = ["public/**"]
  external_node_modules = ["@sparticuz/chromium"]

# Scheduled function
[functions.cache-jadwal-data]
  schedule = "*/10 * * * *"